#ifndef GUARD_CONSTANTS_DYNAMIC_ENCOUNTERS_H
#define GUARD_CONSTANTS_DYNAMIC_ENCOUNTERS_H

enum DynamicEncounterProfile
{
    DYNAMIC_ENCOUNTER_PROFILE_DEFAULT = 0,
    DYNAMIC_ENCOUNTER_PROFILE_DEVELOPMENT_1,
    DYNAMIC_ENCOUNTER_PROFILE_DEVELOPMENT_2,
    DYNAMIC_ENCOUNTER_PROFILE_COUNT,
};

#endif // GUARD_CONSTANTS_DYNAMIC_ENCOUNTERS_H
