#ifndef GUARD_CONSTANTS_TRAINER_RANK_H
#define GUARD_CONSTANTS_TRAINER_RANK_H

enum
{
    TRAINER_RANK_ROOKIE = 0,
    TRAINER_RANK_RISING,
    TRAINER_RANK_ACE,
    TRAINER_RANK_ELITE,
    TRAINER_RANK_MASTER,
    TRAINER_RANK_LEGEND,
    TRAINER_RANK_COUNT
};

#endif // GUARD_CONSTANTS_TRAINER_RANK_H
