#ifndef GUARD_CONSTANTS_WILD_SCALING_H
#define GUARD_CONSTANTS_WILD_SCALING_H

enum WildScalingTier
{
    WILD_SCALING_ROOKIE,
    WILD_SCALING_RISING,
    WILD_SCALING_ACE,
    WILD_SCALING_ELITE,
    WILD_SCALING_MASTER,
    WILD_SCALING_LEGEND,
    WILD_SCALING_TIER_COUNT,
};

#define WILD_SCALING_ANY 0xFFFF

#endif // GUARD_CONSTANTS_WILD_SCALING_H