#ifndef GUARD_CONSTANTS_WORLD_STATE_H
#define GUARD_CONSTANTS_WORLD_STATE_H

enum WorldRegion
{
    WORLD_REGION_HOENN,
    WORLD_REGION_JOHTO,
    WORLD_REGION_KANTO,
    WORLD_REGION_SEVII,
    WORLD_REGION_SINNOH,
    WORLD_REGION_COUNT,
};

enum WorldPhase
{
    WORLD_PHASE_BEGINNING,
    WORLD_PHASE_ROOKIE,
    WORLD_PHASE_RISING,
    WORLD_PHASE_ACE,
    WORLD_PHASE_ELITE,
    WORLD_PHASE_MASTER,
    WORLD_PHASE_LEGEND,
    WORLD_PHASE_COUNT,
};

#endif // GUARD_CONSTANTS_WORLD_STATE_H
